package main

import (
	"context"
	"log"
	"net/http"
	"net/url"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/circuitbreaker"
	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/config"
	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/idempotency"
	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/proxy"
	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/requestid"
	"github.com/mahalaxmiginnam/Asecra_Fabric/internal/retry"
)

const (
	apiPrefix = "/api"
)

func newHandler() (http.Handler, error) {
	cfg := config.Load()

	// ------------------------------------------------------------
	// Upstream
	// ------------------------------------------------------------

	upstream, err := url.Parse(cfg.BackendURL)
	if err != nil {
		return nil, err
	}

	// ------------------------------------------------------------
	// Circuit Breaker
	// ------------------------------------------------------------

	breaker := circuitbreaker.New(
		cfg.CircuitFailureThreshold,
		cfg.CircuitResetTimeout,
	)

	// ------------------------------------------------------------
	// Proxy Executor
	// ------------------------------------------------------------

	executor := &proxy.Executor{
		Client: &http.Client{
			Timeout: 0,
		},

		Upstream: upstream,

		Retry: retry.Controller{
			MaxAttempts: cfg.MaxAttempts,
			BaseDelay:   cfg.BaseDelay,
		},

		Breaker: breaker,

		RequestTimeout: cfg.RequestTimeout,
	}

	// ------------------------------------------------------------
	// Idempotency
	// ------------------------------------------------------------

	idempotencyStore := idempotency.NewStore(
		cfg.IdempotencyTTL,
	)

	idempotencyController := idempotency.NewController(
		idempotencyStore,
	)

	idempotencyMiddleware := idempotency.NewMiddleware(
		idempotencyController,
	)

	// ------------------------------------------------------------
	// Gateway Handler
	// ------------------------------------------------------------

	var handler http.Handler = http.HandlerFunc(
		func(w http.ResponseWriter, r *http.Request) {

			// ----------------------------------------------------
			// Health
			// ----------------------------------------------------

			if r.URL.Path == "/health" {
				w.WriteHeader(http.StatusOK)

				_, _ = w.Write([]byte("ok"))

				return
			}

			// ----------------------------------------------------
			// API Routing
			// ----------------------------------------------------

			if !strings.HasPrefix(
				r.URL.Path,
				apiPrefix+"/",
			) {
				http.NotFound(w, r)

				return
			}

			originalPath := r.URL.Path

			// ----------------------------------------------------
			// Strip /api before forwarding.
			//
			// /api/orders
			//       ↓
			// /orders
			// ----------------------------------------------------

			r.URL.Path = strings.TrimPrefix(
				r.URL.Path,
				apiPrefix,
			)

			if r.URL.Path == "" {
				r.URL.Path = "/"
			}

			// ----------------------------------------------------
			// Execute through:
			//
			// Retry
			// Circuit Breaker
			// Proxy
			// ----------------------------------------------------

			result, err := executor.Execute(
				r.Context(),
				r,
			)

			// Restore client-facing path.
			r.URL.Path = originalPath

			if err != nil {

				log.Printf(
					"gateway: request failed method=%s path=%s request_id=%s error=%v",
					r.Method,
					originalPath,
					r.Header.Get(requestid.Header),
					err,
				)

				// Circuit breaker rejection.
				if err == circuitbreaker.ErrOpen ||
					err == circuitbreaker.ErrBusy {

					http.Error(
						w,
						"upstream temporarily unavailable",
						http.StatusServiceUnavailable,
					)

					return
				}

				http.Error(
					w,
					"upstream request failed",
					http.StatusBadGateway,
				)

				return
			}

			// ----------------------------------------------------
			// Logging
			// ----------------------------------------------------

			log.Printf(
				"gateway: method=%s path=%s status=%d attempts=%d request_id=%s",
				r.Method,
				originalPath,
				result.StatusCode,
				result.Attempts,
				r.Header.Get(requestid.Header),
			)

			// ----------------------------------------------------
			// Write upstream response.
			// ----------------------------------------------------

			if err := result.WriteTo(w); err != nil {
				log.Printf(
					"gateway: response write error request_id=%s error=%v",
					r.Header.Get(requestid.Header),
					err,
				)
			}
		},
	)

	// ------------------------------------------------------------
	// Middleware
	//
	// Request ID is outermost so every request receives a
	// correlation ID, including errors generated by middleware.
	// ------------------------------------------------------------

	handler = idempotencyMiddleware.Handler(handler)

	handler = requestid.Middleware(handler)

	return handler, nil
}

func main() {
	cfg := config.Load()

	handler, err := newHandler()
	if err != nil {
		log.Fatal(err)
	}

	// ------------------------------------------------------------
	// HTTP Server
	// ------------------------------------------------------------

	server := &http.Server{
		Addr:    cfg.GatewayAddr,
		Handler: handler,

		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  30 * time.Second,
	}

	// ------------------------------------------------------------
	// Start Server
	// ------------------------------------------------------------

	go func() {

		log.Printf(
			"Asecra Fabric gateway listening on %s",
			cfg.GatewayAddr,
		)

		if err := server.ListenAndServe(); err != nil &&
			err != http.ErrServerClosed {

			log.Fatalf(
				"gateway server failed: %v",
				err,
			)
		}
	}()

	// ------------------------------------------------------------
	// Graceful Shutdown
	// ------------------------------------------------------------

	stop := make(chan os.Signal, 1)

	signal.Notify(
		stop,
		syscall.SIGINT,
		syscall.SIGTERM,
	)

	<-stop

	log.Println(
		"gateway shutdown initiated",
	)

	// Give active requests time to finish.
	ctx, cancel := context.WithTimeout(
		context.Background(),
		10*time.Second,
	)
	defer cancel()

	if err := server.Shutdown(ctx); err != nil {

		log.Printf(
			"gateway graceful shutdown failed: %v",
			err,
		)

		return
	}

	log.Println(
		"gateway shutdown complete",
	)
}
